services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-ci
    user: root  # Necessário para acessar o docker.sock sem conflito de permissões
    privileged: true
    ports:
      - "8081:8080"
    environment:
      # DOCKER_HOST: unix:///run/user/1000/docker.sock
      DOCKER_HOST: tcp://dind:2375
      JENKINS_HOME_HOST: ./jenkins_home
      TZ: Etc/GMT+3
    volumes:
      - ./jenkins_home:/var/jenkins_home
      #- /run/user/1000/docker.sock:/run/user/1000/docker.sock
    networks:
      - default
      - docker-net
      # - kind
    restart: unless-stopped
    depends_on:
      - dind
  dind:
    image: "docker:29-dind"
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    entrypoint:
      - dockerd
      - --host=tcp://0.0.0.0:2375
    networks:
      docker-net:
        aliases:
          - dind
networks:
  docker-net:
    name: docker-net
